### GET request with a header
GET {{host}}/tasks
Accept: application/json

### GET task $id list
GET {{host}}/tasks/123
Accept: application/json

### POST Create new task
POST {{host}}/tasks
Accept: application/json

### PATCH Create new task
PATCH {{host}}/tasks/123
Accept: application/json

### POST Create new task
DELETE {{host}}/tasks/123
Accept: application/json