### GET request with a header API_KEY
GET {{host}}/tasks
Accept: application/json
X-API-Key:85e71d6e3038f170e13cbf2ba21c0fc2


### GET request with a header
GET {{host}}/tasks
Accept: application/json

### GET task $id list
GET {{host}}/tasks/1
Accept: application/json

### POST Create new task
POST {{host}}/tasks
Accept: application/json
#Content-Type: application/x-www-form-urlencoded
Content-Type: application/json

{"name":"Rasim","priority":1,"is_completed":false}

### PATCH Update Task ID
PATCH {{host}}/tasks/1
Accept: application/json

{"name":"Rasim","priority":1,"is_completed":false}

### DELETE Delete Task ID
DELETE {{host}}/tasks/123
Accept: application/json

